blank_issues_enabled: false
contact_links:
  - name: 工具箱问题（使用中文）
    url: https://github.com/LocalizeLimbusCompany/LLC_MOD_Toolbox/issues
    about: "工具箱出现了问题？请点击这里。"
  - name: GitHub 讨论
    url: https://github.com/orgs/LocalizeLimbusCompany/discussions
    about: "在这里自由讨论LocalizeLimbusCompany的功能和问题，无需模板。"
